server:
  port: 0

spring:
  application:
    name: MEMBER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rlarbtjd951
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    ms:
      selvernine: DEBUG

jwt:
  header: Authorization
  secret: eeb0Bonsp6hstpgEokKhIfmuqWVEtjjpC8EEVRErrgYaisIbYhjEFbNvvALAnXS
  token-validity-in-seconds: 86400

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka